# enemy_color: "red"
enemy_color: "blue"


#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: GPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----USB相机参数-----#####
image_width: 640
image_height: 360
new_image_width: 1280
new_image_height: 720
fov_h: 57.7 #87.7
fov_v: 56.7 
new_fov_h: 37 #67
new_fov_v: 40.9
usb_frame_rate: 60
usb_exposure: 305 #1-80000______250
new_usb_exposure: 320
usb_gamma: 160
usb_gain: 10 #0-96

#####-----相机参数-----#####
camera_dir: configs/camera

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
min_confidence: 0.8

#####-----cboard参数-----#####
quaternion_canid: 0x01
bullet_speed_canid: 0x110
send_canid: 0xff
can_interface: "can0"

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----EKF参数-----#####
ekf:
  q_xyz_acc_var: 100.0   # 位置/速度加速度方差
  q_yaw_acc_var: 75.0    # 角加速度方差
  r_yaw: 4.0e-2          # yaw 观测噪声
  r_pitch: 4.0e-2        # pitch 观测噪声
  r_dist_base: 1.5e-2    # 距离观测噪声基础值

  outpost:
    radius: 0.2765
    armor_num: 3
    p0: [1, 64, 1, 64, 1, 81, 0.4, 100, 1.0e-4, 0, 0]

  base:
    radius: 0.3205
    armor_num: 3
    p0: [1, 64, 1, 64, 1, 64, 0.4, 100, 1.0e-4, 0, 0]

  normal:
    radius: 0.2
    armor_num: 4
    p0: [1, 64, 1, 64, 1, 64, 0.4, 400, 1.0e-5, 1, 1]

#####-----aimer参数-----#####
yaw_offset: -2.5 # degree -2.5
pitch_offset: 0  # degree 2
comming_angle: 70 # degree
leaving_angle: 30 # degree
decision_speed: 7 # rad/s
high_speed_delay_time: 0.066 # s
low_speed_delay_time: 0.015 # s

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#####-----decider参数-----#####
mode: 1

#####-----buff_detector参数-----#####
detect:
  contrast: 1
  brightness: 
    blue: -120
    red: -100
  brightness_threshold:
    blue: 120
    red: 80
  morphology_size:
    blue: 3
    red: 2
  dilate_size: 1
  # canny_low_threshold: 100
  # canny_high_threshold: 180
  # approx_epsilon: 1.0
  R_contours_min_area: 1
  R_contours_max_area: 600
  fanblades_head_contours_min_area: 300
  fanblades_head_contours_max_area: 8000
  fanblades_body_contours_min_area: 1000
  fanblades_body_contours_max_area: 4000
  standard_fanblade_path: ./assets/standard_fanblade.jpg

#####-----buff_aimer参数-----#####
aim_time: 0.200 # s
wait_time: 0.050 # s
predict_time: 0.300 # s

#####-----remote_logger-----#####
remote_logger:
  remote_host: "127.0.0.1"
  control_port: 15000
  enable_remote: true
  enable_local: true
  log_dir: "./logs"
  var_buffer_size: 1024
  img_buffer_size: 10
  img_width: 640
  img_quality: 50
  heartbeat_interval_ms: 500
  sender_name: "mvs"
  register_retry_ms: 3000
